name: "Install & Build"
description: "Setup pnpm, install dependencies, lint & build"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Use Node.js 19
      uses: actions/setup-node@v3
      with:
        node-version: 19.x
        cache: "pnpm"

    - name: Install, Lint & Build
      shell: bash
      run: |
        pnpm install --frozen-lockfile
        pnpm lint
        pnpm build
