/**
 * Differents sources of request results.
 * maggregor_cache: when the request is answered from the Maggregor cache
 * maggregor_mv: when the request is processed by Maggregor
 * mongodb: when the request is delegated to the MongoDB server
 */
export type RequestSourceType = 'maggregor_cache' | 'maggregor_mv' | 'mongodb';
export type RequestType =
  | 'find'
  | 'aggregate'
  | 'count'
  | 'distinct'
  | 'unknown';
export interface IRequest {
  // Unique identifier of the request.
  id: string;
  // The request id a number that is generated by the client and is used to identify a request.
  mongoRequestID: number;
  // The db name where the request is made.
  db: string;
  // The collection name where the request is made.
  collName: string;
  // The start time of the request.
  startAt?: Date;
  // The end time of the request.
  endAt?: Date;
  // For `aggregate` requests, the pipeline is the aggregation pipeline.
  pipeline?: Record<string, unknown>[];
  // For `find` requests, the filter is the query object.
  filter?: Record<string, unknown>;
  // For `count` requests, the query is the query object.
  query?: Record<string, unknown>;
  // For `distinct` requests, the key is the field name.
  key?: string;
  // For read requests except `aggregate`, the limit is the maximum number of documents to return.
  limit?: number;
  // The source of the request results.
  requestSource?: RequestSourceType;
  // The type of the request.
  type: RequestType;
}
