name: Benchmarks
on:
  workflow_dispatch:
    inputs:
      tests:
        type: choice
        description: Scenarios to run
        default: "Run all scenarios"
        options:
          - "Run all scenarios"
          - "Run 'aggregate' scenario"
          - "Run 'count' scenario"
          - "Run 'distinct' scenario"
          - "Run 'find' scenario"
      docs:
        type: choice
        description: Number of documents
        default: "100k"
        options:
          - "0"
          - "10"
          - "100"
          - "1k"
          - "10k"
          - "100k"
          - "1m"

  pull_request:
    branches:
      - main

permissions:
  deployments: write
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite-setup

      - name: Run benchmark
        run: |
          TEST_NAME=${{ github.event.inputs.tests }}
          if [ "$TEST_NAME" != "Run all scenarios" ]; then
            SCENARIO="--name=$(echo $TEST_NAME | sed 's/Run //; s/ //')"
            pnpm benchmark --docs "${{ github.event.inputs.docs }}" --flush $SCENARIO
          else
            pnpm benchmark --docs "${{ github.event.inputs.docs }}" --flush
          fi
