name: Benchmarks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite-setup

      - name: Run benchmark
        run: pnpm benchmark --flush

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "Benchmark"
          tool: "benchmarkjs"
          fail-on-alert: true
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true
          output-file-path: "benchmarks/.results/10k-aggregate.txt"
          # Enable Job Summary for PRs
          summary-always: true
          # Push benchmark results to gh-pages branch
          auto-push: true

      - name: Store benchmark result 2
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "Benchmark"
          tool: "benchmarkjs"
          fail-on-alert: true
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true
          output-file-path: "benchmarks/.results/10k-find.txt"
          # Enable Job Summary for PRs
          summary-always: true
          # Push benchmark results to gh-pages branch
          auto-push: true
