name: Release
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite-setup

      - name: Run benchmark
        run: pnpm benchmark --name 10k-aggregate --output

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "benchmarkjs"
          output-file-path: "benchmarks/.results/10k-aggregate.txt"
