name: Benchmarks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  deployments: write
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite-setup

      - name: Run benchmark
        run: pnpm benchmark --flush

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Aggregate Benchmark
          tool: "benchmarkjs"
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          output-file-path: benchmarks/.results/10k-aggregate.txt
          extra-output-file-paths: |
            benchmarks/.results/10k-find.txt
          summary-always: true
          auto-push: true
