name: Benchmarks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite-setup

      - name: Run benchmark
        run: pnpm benchmark --name 10k-aggregate --flush

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "benchmarkjs"
          fail-on-alert: true
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true
          output-file-path: "benchmarks/.results/10k-aggregate.txt"
