name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-pnpm:
    runs-on: ubuntu-latest

    steps:
      - name: Install pnpm
        run: curl -L https://unpkg.com/@pnpm/self-installer | node

  install-dependencies:
    needs: install-pnpm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  build:
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Build project
        run: pnpm build

  test-unit:
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Run unit tests
        run: pnpm test:unit

  test-integration:
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Run integration tests
        run: pnpm test:integration

  test-e2e:
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Run e2e tests
        run: pnpm test:e2e
