name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: "pnpm"

      - name: Install & Build & Lint
        run: |
          sudo apt install libssl-dev && echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list && sudo apt-get update && sudo apt-get install libssl1.1
          pnpm install --frozen-lockfile
          pnpm lint
          pnpm build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            dist/
            node_modules/

  unit:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: "pnpm"

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: Install & Lint
        run: |
          pnpm install --frozen-lockfile
          pnpm lint

      - name: Run unit tests
        run: pnpm test:unit

  integration:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: "pnpm"

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: Install & Lint
        run: |
          pnpm install --frozen-lockfile
          pnpm lint

      - name: Run integration tests
        run: pnpm test:integration

  e2e:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: "pnpm"

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: Install & Lint
        run: |
          pnpm install --frozen-lockfile
          pnpm lint

      - name: Run e2e tests
        run: pnpm test:e2e
