name: All package tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Run tests for parser
        run: pnpm install && pnpm build
        working-directory: packages/mongodb-parser

      - name: Run tests for core
        run: pnpm install && pnpm test
        working-directory: packages/core

      - name: Install libssl1.1 for MongoDB Memory Server (tests)
        run: sudo apt install libssl-dev && echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list && sudo apt-get update && sudo apt-get install libssl1.1

      - name: Run tests for server
        run: pnpm install && pnpm test
        working-directory: packages/server
